echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "We are learning Branching"
echo "Git fork and git clone"
echo "Hi everyone today is my 1t day for use github"
echo "I am proper understand basic git work"